### PR TITLE
Fix python package import and C++ run dependencies

### PR DESCRIPTION
**Pull request by zhujun98**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR is supposed to fix outputing of C++ (a head-only library) and the Python binding simultaneously:

- In the current version, The Python library is installed but cannot be imported, and I cannot see the package name "pyfoamalgo" after typing "conda list".

- For the C++ part, the dependencies are added. It is required when users build their own library using the head-only library.

In the very first PR, I gave up using `outputs` because of some werid errors.

### CODE REVIEW

**Comment by zhujun98** [comment]
@conda-forge-admin

**Comment by zhujun98** [comment]
Hi @marcelotrevisani Can I merge this kind of change without the review from an administrator?

By the way, I guess there may be a bug in `outputs`. I must put even a single line of script

```
$PYTHON -m pip install . --no-deps -vv
```

In a file. Otherwise, it raises error because of some command cannot be copied.

**Comment by marcelotrevisani** [comment]
> Hi @marcelotrevisani Can I merge this kind of change without the review from an administrator?
> 
> By the way, I guess there may be a bug in `outputs`. I must put even a single line of script
> 
> ```
> $PYTHON -m pip install . --no-deps -vv
> ```
> 
> In a file. Otherwise, it raises error because of some command cannot be copied.

Yeah, you need to add a script with just that command when using outputs, it is a point of improvement on conda-build

Sure, you can merge it, you are the maintainer of this package now, but if you have any problem/question please feel free to ping conda-forge/core  , I will be notified as well. You can also ping me directly

Cheers!

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
We also have a documentation to guide you in maintaining packages
https://conda-forge.org/docs/maintainer/updating_pkgs.html

**Review by marcelotrevisani — APPROVED** [review]

**Comment by zhujun98** [comment]
Thanks a lot! Now I know how to use `@conda-forge-admin , please rerender` correctly :-)

**Pull request merged**
